name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Asentaa riippuvuude front ja back
      - name: Install backend deps
        run: npm ci --prefix backend

      - name: Install frontend deps
        run: npm ci --prefix frontend

      # Linttaus
      - name: Check style
        run: npm run lint:all

      # Testaukset
      - name: Testing backend
        run: npm test --prefix backend
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}

      - name: Testing frontend
        run: npm test -prefix frontend

      # Build
      - name: Build frontend
        run: npm run build --prefix frontend
