name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI}}
      SECRET: ${{ secrets.SECRET}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Asentaa riippuvuudet
      - name: Install root dependencies
        run: npm ci
      - name: Install backend dependencies
        run: npm ci --prefix backend
      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      # Build frontend
      - name: Build frontend
        run: npm run build --prefix frontend

      # Käynnistetään backend
      - name: Start backend
        run: nohup npm run start:test --prefix backend & echo $! > backend.pid

      # Asennetaan playwright selaimet
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Ajetaan playwright testit
      - name: Run Playwright tests
        run: npx wait-on http://localhost:3003 && npx playwright test

      # Sulkee backendin
      - name: Stop backend
        run: kill $(cat backend.pid)

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
